name: AUSNC Licence
text: >
  <p class="p1"><b>1. Dictionary </b>1.1 The <b>Dictionary </b>at the end of these Terms defines some words. Generally,
    the words</p>
  <p class="p1">beginning with capital letters are defined, unless the contrary intention appears.</p>
  <p class="p1"><b>2. About You</b></p>
  <p class="p1">2.1 To Use this Site You must be 18 years of age or older. By agreeing to these Terms, You are
    representing that You are at least 18 years of age. If you are not at least 18 years of age, You may not enter the
    Site or use any of the Material. If You are under 18 years of age and require access, please speak with your school or
    university.</p>
  <p class="p1">2.2 Whether You are a Public User or a Trusted User, You must agree to these Terms each and every time You
    start a Session. If You are a Trusted User, We may try to let You know by email if these Terms have changed, but it
    remains Your responsibility to read and agree to them for each Session.</p>
  <p class="p1">2.3 If You are a Trusted User, You must also enter the Account details provided to You. You must not allow
    any other person to use Your Account and must keep the details of Your Account secure.</p>
  <p class="p1"><b>3. Your Use of the Site</b></p>
  <p class="p1">3.1 Subject to this clause 3, all Intellectual Property Rights in the Material on this Site are reserved
    by the owners and licensees of those rights, which are protected under the laws of Australia and other countries.</p>
  <p class="p1">3.2 We grant You permission to Use the Site and the Material on it for a Session according to these Terms.
    This permission constitutes a limited licence and may not be, sub-licensed, transferred, assigned, charged or
    otherwise encumbered by You. You will not have access to Sensitive Material unless You are a Trusted User.</p>
  <p class="p1">3.3 We also grant You permission to download one copy only of a reasonable number of single Items for use
    by You alone off-line in conjunction with research and study only. This licence does NOT otherwise include the right
    to copy or reproduce the Material and IN NO CIRCUMSTANCES does it include the right to modify, adapt, distribute,
    display, transmit, perform or broadcast any Material, or otherwise cause it to be shown or heard in public or its use
    for any commercial purpose (including commercially exploiting the Material). This permission constitutes a limited
    licence and may not be, sub-licensed, transferred, assigned, charged or otherwise encumbered by You. Again, you will
    not have access to Sensitive Material unless You are a Trusted User.</p>
  <p class="p1">© Australian National Corpus Inc, 2012.</p>
  <p class="p1"><b>AusNC Terms of Use </b>2</p>
  <p class="p1">3.4 Despite clauses 3.2 and 3.3, it will not be a breach of these Terms if Your use of the Material
    constitutes Fair Dealing or is otherwise allowed by statute despite the application of these Terms.</p>
  <p class="p1">3.5 We may cancel or suspend Your Session at any time for any reason without any notice to You.</p>
  <p class="p1">3.6 We may change the Site or the Material on it at any time without notice to You.</p>
  <p class="p1">3.7 If You are a Trusted User, You acknowledge that provision of Your Account is entirely in Our
    discretion and We may cancel or suspend Your Account at any time for any reason without prior notice to You.</p>
  <p class="p1">3.8 We request that you acknowledge any Material lawfully referred to by You in accordance with the
    guidelines we may publish on this Site from time to time.</p>
  <p class="p1"><b>4. Limitation of Liability &amp; Indemnity</b></p>
  <p class="p1">4.1 References in this clause to ‘Us’ or ‘We’ apply also to the benefit of any of Our officers, employees,
    subcontractor or agents, as well as to the contributors of Material to the AusNC.</p>
  <p class="p1">4.2 Your use of this Site is on an ‘as is’ basis and, to the extent permitted by law and subject to this
    clause 4, You acknowledge that We make no representation or warranty (express or implied) about, and will not be
    liable to You for:</p>
  <p class="p1">(a) the accuracy, content, legality (including about the correct ownership of Intellectual Property
    Rights), security (including the presence of viruses or other malicious code) or completeness, of the Site or any
    Material; or</p>
  <p class="p1">(b) access, availability or reliability of the Site.</p>
  <p class="p1">4.3 To the extent permitted by law and subject to clause 4.4, We also exclude all implied terms,
    representations and warranties, whether statutory or otherwise, relating to the subject matter of these Terms.</p>
  <p class="p1">4.4 Where any statutory term cannot be excluded under clause 4.3, such a term is deemed to be included in
    these Terms. Where Our statutory liability cannot be excluded by law, and to extent that the law allows, it will be
    limited to the greatest extent the law permits.</p>
  <p class="p1">4.5 Subject to clause 4.4, You agree to indemnify Us and hold Us harmless in respect of any: (a) Claim You
    might make against Us in relation to the use of the Site or Material by You; (b) any breach by You of these Terms;
    and</p>
  <p class="p1">(c) anyClaimanyotherpersonmaymakeagainstUsbecauseoftheuseofthisSiteor the Material by You, including
    because You have infringed the Intellectual Property Rights of anyone,</p>
  <p class="p1">to the full extent of such Claim, as well as in relation to Our legal costs in defending any such
    Claim.</p>
  <p class="p1"><b>5. Security &amp; access</b></p>
  <p class="p1">5.1 You must maintain reasonable data security measures to ensure that the Site or Material is not subject
    to unauthorised access.</p>
  <p class="p1">5.2 You will not seek to disrupt or go around the security measures on the Site or use any robots, spiders
    or web crawlers (being devices which input data faster than a human being) to access the Site or Material.</p>
  <p class="p1">© Australian National Corpus Inc, 2012.</p>
  <p class="p1"><b>AusNC Terms of Use </b>3</p>
  <p class="p1"><b>6. Sensitive Material</b></p>
  <p class="p1">If You are a Trusted User You will have access to Sensitive Material. You agree to keep such Material
    confidential and not to share its content with anyone who is not also a Trusted User without Our permission.</p>
  <p class="p1"><b>7. Professional care</b></p>
  <p class="p1">If You are a Trusted User, You must also exercise due professional care and judgement and only make use of
    the Material, as permitted by these Terms, in accordance with the highest standards of ethical and academic
    practice.</p>
  <p class="p1"><b>8. Reading this Licence</b></p>
  <p class="p1">These rules apply to reading these Terms, unless the contrary intention appears: • a reference to a clause
    is to a clause of these Terms; • a reference to a person includes a body corporate; • the singular includes the plural
    and vice versa;</p>
  <p class="p1">• a reference to legislation, includes subordinate legislation made under it;</p>
  <p class="p1">• headings do not affect the meaning of clauses;</p>
  <p class="p1">• the other grammatical forms of words used in these Terms have a corresponding meaning;</p>
  <p class="p1">• neither these Terms, nor any clause or amendments to them, are to be construed against a party merely
    because that party drafted them.</p>
  <p class="p1"><b>9. General</b></p>
  <p class="p1">9.1 <i>Waiver. </i>We will not waive any of Our rights under these Terms except in writing. 9.2 <i>Entire
    agreement. </i>These Terms are the entire agreement between You and Us in relation</p>
  <p class="p1">to its subject matter.</p>
  <p class="p1">9.3 <i>Law. </i>The law of State of Queensland, Australia applies to these Terms. Each party submits to
    the jurisdiction of the courts in Brisbane, Queensland, Australia. To the extent the law permits, the Site is deemed
    to be located in Brisbane, Queensland, Australia.</p>
  <p class="p1">9.4 <i>Related steps. </i>You agree to do all things (such as the execution of further documents) as may
    be necessary to give effect to these Terms.</p>
  <p class="p1">9.5 <i>Severability. </i>If any part of these Terms is held to be invalid or unenforceable, it will be
    severed from the rest of the Terms to the most limited extent necessary so as not to affect the operation of the
    remaining clauses.</p>
  <p class="p1"><b><i>Dictionary</i></b></p>
  <p class="p1"><b>Account </b>means a user account with a username and password. <b>AusNC </b>means the Australian
    National Corpus database, which contains the Material.</p>
  <p class="p1">© Australian National Corpus Inc, 2012.</p>
  <p class="p1"><b>AusNC Terms of Use </b>4</p>
  <p class="p1"><b>Claim </b>includes all proceedings, suits, actions and claims, of any kind, under any law and in any
    jurisdiction, whether in law or in equity, and including any claim based on negligence or any breach of privacy or
    confidentiality, or the defamation of any person, and whether for damages, compensation, costs, losses or any kind
    (including indirect or consequential loss, such as loss of future profits or goodwill) or for any other amount or
    order.</p>
  <p class="p1"><b>Fair Dealing </b>has the meaning given to it in Part III, Division 3 of the <i>Copyright Act 1968 </i>(Cth),
    as amended from time to time.</p>
  <p class="p1"><b>Intellectual Property Rights </b>means copyright and, where the context allows, moral rights and
    performers’ rights.</p>
  <p class="p1"><b>Item </b>means an individual item of the Material from the collection comprising the AusNC.</p>
  <p class="p1"><b>Material </b>includes all material accessible via the Site from time to time such as collections,
    texts, photographs, video recordings (including cinematographic films) and sound recordings, whether in or not in
    electronic form, and any annotations, commentary or other material made available in connection with that material.
  </p>
  <p class="p1"><b>Personal Information </b>has the meaning given to it in the <i>Privacy Act 1988 </i>(Cth).</p>
  <p class="p1"><b>Public User </b>means a User without an Account.</p>
  <p class="p1"><b>Sensitive Material </b>means Material which has been identified by Us as sensitive, including because
    it is not suitable for general public access, it contains the Personal Information of any person, because it is
    culturally sensitive, or because there are other limits upon its use, including as imposed by a contributor to the
    AusNC.</p>
  <p class="p1"><b>Session </b>means a single continuous period of access to the Site, beginning when You are granted
    access and ending when that access is terminated by You, Us or for any technical reason, whether or not in our
    control.</p>
  <p class="p1"><b>Site </b>means the website operated by Us and accessible at www.ausnc.org.au and, unless the contrary
    intention appears, the AusNC as accessible via that Site.</p>
  <p class="p1"><b>Terms </b>means these terms and conditions of use. <b>Trusted User </b>means a User to whom we have
    previously provided an Account. <b>Use </b>means ONLY:</p>
  <p class="p1">• viewing and navigating the Site as intended; AND</p>
  <p class="p1">• viewing or listening to Material on the Site on-line during a Session,</p>
  <p class="p1">BUT does NOT otherwise include the right to copy or reproduce the Material and in NO CIRCUMSTANCES does it
    include the right to modify, adapt, distribute, display, transmit, perform or broadcast any Material, or otherwise
    cause it to be shown or heard in public, downloading Material for use after a Session (except under clause 3.3) or the
    use of Material for any commercial purposes (including commercially exploiting the Material).</p>
  <p class="p1"><b>User </b>means a person granted access to the Site and includes Public Users and Trusted Users, unless
    the contrary intention appears.</p>
