name: AusTalk Terms of Use
text: >
  <p>
    Terms of Use for the AusTalk Corpus for Project Members
  </p>
  <br/>
  <p>
    The AusTalk corpus has been collected by a consortium of Universities under the Big ASC project, funded by the ARC,
    and it is intended to be made broadly available for research on Australian speech and language. Unfortunately the
    terms under which we can release the data more widely are still under negotiation with our legal advisors. Members
    of the University partners that collected the data are free to use the data, as this was part of the Big ASC project
    agreement, and there are no restrictions on the use of the data as long as it is for research. However, you must not
    share or further distribute any data from the AusTalk corpus outside of the Big ASC project partners. This includes
    the demographic descriptions of participants (meta-data) as well as the audio and video recordings themselves.
  </p>
  <br/>
  <p>
    It is a condition of use that any annotation or transcription that is done with the AusTalk corpus data should be
    contributed back to the project for use by others. Any such contribution will be stored in a way that identifies you
    as the creator.
  </p>
  <br/>
  <p>
    Attribution
  </p>
  <br/>
  <p>
    When you access, use, reproduce, exploit or make reference in publications to the AusTalk Content, you will
    attribute the ownership of the AusTalk Content to us by referring to the following published paper referenced below
    or as otherwise notified by us to you:
  </p>
  <br/>
  <p>
    Burnham, D., Estival, D., Fazio, S., Viethen, J. Cox, J., Dale, R., Cassidy, S., Epps, J., Togneri, R., Wagner, M.,
    Kinoshita, Y., Göcke, R., Arciuli, J., Onslow. M., Lewis, T., Butcher, A., & Hajek, J. (2011) Building an
    audio-visual corpus of Australian English: large corpus collection with an economical portable and replicable Black
    Box. Proceedings of 12th Annual Conference of the International Speech Communication Association (Interspeech, 2011),
    ISSN 1990-9772, pp 841-844.
  </p>
