name: AusTalk Terms of Use
text: >
  <p>Terms of Use for the Austalk Corpus for Project Members</p>
  <br/>
  <p>The Austalk corpus has been collected by a consortium of Universities
  and is intended to be made broadly available for research on Australian
  speech and language. Unfortunately we are still negotiating the terms
  under which we can release different parts of the data with our legal
  advisors. The main issue being protecting the privacy of the participants.
  As a consequence, we cannot yet make the data widely available.</p>
  <br/>
  <p>Members of the University partners that collected the data are
  free to use the data however; this was part of the original agreement
  between the partners. There are no restrictions on what you can
  do with the data as long as you are doing research. Commercial activities
  with the data may need to be negotiated between the parties (we"re not
  100% certain of this).</p>
  <br/>
  <p>However, as a consequence of the uncertainty around broader distribution
  of the data you must not share or further distribute any data from
  the Austalk corpus outside of the partner Universities. This includes
  the demographic descriptions of participants (meta-data) as well as
  the audio and video recordings themselves.</p>
  <br/>
  <p>Any annotation or transcription that you do for corpus data should be
  contributed back to the project for use by others. We will store
  any data you contribute on the server in a way that identifies you
  as the creator.</p>
  <br/>
  <p>How to access the data</p>
  <br/>
  <p>We are working on a more flexible way to identify and download parts
  of the corpus. Until then, you can get access to the data by mounting
  the server drive using WebDav. Some instructions are on the Trac wiki:</p>
  <br/>
  <p>https://austalk.edu.au/trac/wiki/MountingDataDrive</p>
  <br/>
  <p>This is now password protected so you will need to ask Steve Cassidy
  (steve.cassidy@mq.edu.au) for a username/password for your institution.</p>