name: ClueWeb Terms of Use
text: >
  <h2>Individual Agreement to use the ClueWeb09 Web Research Collections</h2>
  <p>I hereby agree to use the Information designated as the ClueWeb09 Text Research&nbsp;Collection(s) (the "Information"). By signing this
  Individual Agreement (&ldquo;Agreement&rdquo;)&nbsp;with the Organization, I hereby agree to abide by the following understandings, terms
  and&nbsp;conditions. These understandings, terms and conditions apply equally to all or to part of the&nbsp;Information, including any
  updates or new versions of the Information supplied under this&nbsp;Agreement.</p>
  <p>&nbsp;</p>
  <h3>Copyright&nbsp;</h3>
  <p>&nbsp;</p><ol>
  <li>The Information as been obtained by crawling the Internet. Due to the amount of&nbsp;Information it has not been practicable to obtain
  permission from copyright owners to&nbsp;provide the Information for the uses permitted under this Agreement (&ldquo;Permitted Uses&rdquo;).&nbsp;</li>
  <li>I understand that all the documents in the Information are documents which have been at&nbsp;some time made publicly available on the Internet and
  which have been collected using a&nbsp;process which respects the commonly accepted methods (such as robots.txt) for indicating&nbsp;that the documents
  should not be so collected.&nbsp;</li>
  <li>Owners of copyright in individual documents may choose to request deletion of these&nbsp;documents from the Information.&nbsp;</li>
  <li>The limitation on permitted use contained in the following section is intended to reduce the&nbsp;risk of any action being brought by
  copyright owners, but if this happens the Organization&nbsp;has agreed under its Organization Agreement to bear all associated liability.&nbsp;</li>
  </ol><p>&nbsp;</p>
  <h3>Permitted Uses&nbsp;</h3>
  <p>&nbsp;</p>
  <ol><li>The Information may only be used for research and development of natural-language-processing, Information-retrieval or document-understanding systems.</li>
  <li>Summaries, analyses and interpretations of the linguistic properties of the Information may&nbsp;be derived and published, provided it is not possible
  to reconstruct the Information from&nbsp;these summaries.&nbsp;</li>
  <li>Small excerpts of the Information may be displayed to others or published in a scientific or&nbsp;technical context, solely for the purpose of describing
  the research and development carried&nbsp;out and related issues.&nbsp;</li>
  <li>All efforts must be made not to infringe the rights of any third party including, but not&nbsp;limited to, the authors and publishers of any excerpts used
  in accordance with clause 3&nbsp;above in this &ldquo;Permitted Uses&rdquo; section.&nbsp;</li>
  </ol><p>&nbsp;</p>
  <h3>Agreement to Delete Data on Request&nbsp;</h3>
  <p>&nbsp;</p><p>I undertake to delete within thirty days of receiving notice all copies of any nominated document&nbsp;that is part of the Information whenever
  requested to do so by either:&nbsp;</p>
  <p>&nbsp;</p><ol><li>Carnegie Mellon University; or&nbsp;</li>
  <li>the owner of copyright for the particular document.&nbsp;</li>
  </ol><p>&nbsp;</p>
  <p>Because my Organization has entered into an Organization Agreement with Carnegie Mellon, I&nbsp;understand that it may receive such notices from Carnegie
  Mellon and/or copyright holders. In&nbsp;that case, I will immediately comply with any instructions from my Organization regarding the&nbsp;deletion of the
  pertinent Information.&nbsp;</p>
  <p>&nbsp;</p>
  <h3>Access to the Information by Individuals&nbsp;</h3>
  <p>&nbsp;</p>
  <p>I understand that the Organization has agreed to certain obligations in respect of my access in an&nbsp;Agreement with Carnegie Mellon University and I
  agree to use the Information only for the&nbsp;Permitted Uses and to comply with those obligations in the Agreement as they affect me. Those&nbsp;obligations
  are that the Organization:&nbsp;</p>
  <p>&nbsp;</p><ol>
  <li>must control access to the Information by individuals and may only grant access to people&nbsp;working under its control, i.e., its own employees,
  consultants under written agreement to&nbsp;the Organization, or individuals providing service to the Organization under written&nbsp;agreement;&nbsp;</li>
  <li>must ensure that before being given access to the Information I complete and submit this&nbsp;Individual Agreement form;&nbsp;</li>
  <li>must terminate my access when I no longer require access for my work for the Organization&nbsp;and/or I am no longer employed by (and/or under contract
  with, as applicable) the&nbsp;Organization;&nbsp;</li>
  <li>remains responsible for any breach of this Individual Agreement form by me;&nbsp;</li>
  <li>shall retain the applications of all persons ever granted access to the Information and make&nbsp;them available upon request to any of the copyright
  holders and to Carnegie Mellon&nbsp;University;&nbsp;</li>
  <li>shall maintain a list of people with current and recently-terminated access to the&nbsp;Information and make it
  available to Carnegie Mellon University on request; and&nbsp;</li>
  <li>must make sure that I only display the Information to or share the Information with persons&nbsp;whom my Organization lists as having access to the Information.</li>
  </ol><p>&nbsp;</p>
  <h3>No Warranty; Disclaimers&nbsp;</h3>
  <p>&nbsp;</p>
  <p>NO WARRANTY IS GIVEN BY CARNEGIE MELLON IN RELATION TO THE&nbsp;INFORMATION OR THE USE(S) TO WHICH THE INFORMATION MAY BE PUT BY THE&nbsp;ORGANIZATION
  OR THE FITNESS OR SUITABILITY OF THE INFORMATION FOR ANY&nbsp;PARTICULAR PURPOSE OR UNDER ANY SPECIAL CONDITIONS REGARDLESS OF&nbsp;WHETHER ANY SUCH
  PARTICULAR PURPOSE OR SPECIAL CONDITIONS ARE OR&nbsp;HAVE BEEN MADE KNOWN TO THE UNIVERSITY PRIOR TO, OR DURING, THE&nbsp;PERIOD OF THIS AGREEMENT.
  ALL CONDITIONS AND WARRANTIES EXPRESS OR&nbsp;IMPLIED, WHETHER ARISING UNDER STATUTE OR UNDER COMMON LAW,&nbsp;INCLUDING BUT NOT LIMITED TO CONDITIONS
  AND WARRANTIES AS TO QUALITY,&nbsp;MERCHANTABILITY AND FITNESS FOR PURPOSE ARE HEREBY EXCLUDED.&nbsp;CARNEGIE MELLON SHALL NOT BE LIABLE TO ORGANIZATION
  OR ANY THIRD&nbsp;PARTY FOR LOSS OF PROFITS OR FOR INCIDENTAL, INDIRECT, SPECIAL OR&nbsp;CONSEQUENTIAL DAMAGES FOR ANY REASON WHATSOVER ARISING OUT OF
  OR&nbsp;RELATING TO THIS AGREEMENT (INCLUDING ANY BREACH OF THIS AGREEMENT),&nbsp;EVEN IF CARNEGIE MELLON HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH&nbsp;DAMAGES
  OR HAS OR GAINS KNOWLEDGE OF THE EXISTENCE OF SUCH&nbsp;DAMAGES.&nbsp;</p>
  <p>&nbsp;</p>
  <h3>Termination&nbsp;</h3>
  <p>&nbsp;</p>
  <p>Either Carnegie Mellon University or the Organization may terminate this Agreement at any time&nbsp;by notifying the other party in writing. On
  termination of the Agreement by either Carnegie&nbsp;Mellon University or the Organization or termination of my access by the Organization, I shall&nbsp;return
  to the Organization or destroy all copies of the Information.&nbsp;</p>
  <p>&nbsp;</p>
  <h3>Applicable Law; Disputes&nbsp;</h3>
  <p>&nbsp;</p>
  <p>This Individual Application is governed by the laws of the state of Pennsylvania in the United&nbsp;States of America.&nbsp;</p>
  <p>&nbsp;</p>
  <h3>Miscellaneous&nbsp;</h3>
  <p>&nbsp;</p>
  <p>If any portion of this Agreement is determined by any court or governmental agency of competent&nbsp;jurisdiction to violate applicable law or otherwise
  not to conform to requirements of law, then the&nbsp;rest of the Agreement will remain in effect and the parties will substitute a suitable and
  equitable&nbsp;provision for the invalid/unenforceable provision in order to carry out the original intent and&nbsp;purpose of the original Agreement.
  I may not assign any or all of my rights and/or obligations&nbsp;under this Agreement without the prior written consent of both Carnegie Mellon and
  Organization,&nbsp;which consent may be granted or withheld in their sole discretion. Any attempted assignment in&nbsp;violation of this section shall
  be void and of no effect. This Agreement constitutes the entire&nbsp;agreement and my entire understanding regarding access to and use of the Information
  and&nbsp;supersedes all previous agreements and understandings of mine relating to the subject matter of&nbsp;this Agreement. The Agreement may not be
  altered, amended, or modified except by a written&nbsp;instrument signed by me and by the duly authorized representatives of both Carnegie Mellon
  and&nbsp;the Organization.</p>
  <p>&nbsp;</p>
  <p>I hereby execute this Agreement in favor and for the benefit of the Organization, with the&nbsp;understanding that Carnegie Mellon is an intended
  third party beneficiary of this Agreement.</p>