name: LLC Terms of Use
text: >
  <p>
    <span>
      The LLC Lecture corpus is available for members of the Liberated Learning Consortium to carry out related
      research activities. The term &ldquo;the Content&rdquo; shall mean the lecture corpus of the LLC.
      <span style=\"\">&nbsp;</span>
    </span>
  </p>
  <br/>
  <ol>
    <li>
      The Content will be used by [Consortium Member] solely for the purposes of academic research for purposes
      authorized under the LLC Membership Agreement.
    </li>
    <li>
      <span style=\"text-align: justify;\">
        [Consortium Member] shall not transfer, make available or otherwise provide the Content to any third party
        without the prior written consent of UMass Boston.
      </span>
    </li>
    <li>
      <span style=\"text-align: justify;\">
        [Consortium Member] shall have the right to store, display, and, if applicable, perform the Content only to the
        extent needed to conduct research activities as authorized hereunder.
      </span>
    </li>
    <li>
        <span style=\"text-align: justify;\">
        It is understood that this Agreement in no way grants [Consortium Member]
        a license to use the Content for any commercial purpose, including the development of copyrightable works,
        patents or patentable subject matter.
      </span>
    </li>
    <li>
      <span style=\"text-align: justify;\">
      [Consortium Member] agrees to use the Content in compliance with all applicable statutes and regulations.
      </span>
    </li>
    <li>
      <span style=\"text-align: justify;\">
      UMass Boston MAKES NO REPRESENTATIONS, AND EXTENDS NO WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, WITH
      RESPECT TO THE CONTENT.
      </span>
      <span style=\"text-align: justify;\">&nbsp; </span>
      <span style=\"text-align: justify;\">
      THERE ARE NO EXPRESS OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR THAT THE USE
      OF THE MATERIAL WILL NOT INFRINGE ANY PATENT, COPYRIGHT, TRADEMARK, OR OTHER RIGHTS.</span>
    </li>
    <li>
      <span style=\"text-align: justify;\">
      [Consortium Member] assumes all liability for damages which may arise from its breach of this Agreement.
      </span>
      <span style=\"text-align: justify;\">&nbsp;</span>
    </li>
  </ol>
  <br/>
  <p>
    To access the Content, your institution must be a member of the Liberated Learning Consortium.&nbsp; For
    membership information, please visit <a href=\"http://www.liberatedlearning.com\">www.liberatedlearning.com</a> or
    contact <a href=\"mailto:liberated.learning@umb.edu\">liberated.learning@umb.edu</a>
  </p>