PROJECT_NAME = 'Alveo'
PROJECT_PREFIX_NAME = 'alveo'
PROJECT_VOCABULARY_PREFIX_NAME = 'alveov'
PROJECT_BASE_URI = 'http://alveo.edu.au/'
PROJECT_SCHEMA_LOCATION = "#{PROJECT_BASE_URI}schema/"
PROJECT_VOCABULARY_LOCATION = "#{PROJECT_BASE_URI}vocabulary/"
