common: &common
  # this is to map attributes as described in http://aaf.edu.au/technical/aaf-core-attributes/
  # to their respective field in the database
  # uncomment them if need be
  user-mapping:
    cn: ""
    displayname: ""
    edupersontargetedid: ""
    edupersonscopedaffiliation: ""
    edupersonprincipalname: ""
    mail: email
    givenname: first_name
    surname: last_name

development:
  <<: *common
  hostname: https://hcsvlab.intersect.org.au
  secret_token:
  aaf_rc_login_url:

qa:
  <<: *common
  hostname: https://ic2-hcsvlab-test4-vm.intersect.org.au
  secret_token:
  aaf_rc_login_url:

qa2:
  <<: *common
  hostname: https://ic2-hcsvlab-qa2-vm.intersect.org.au
  secret_token:
  aaf_rc_login_url:

staging:
  <<: *common
  hostname: https://ic2-hcsvlab-staging1-vm.intersect.org.au
  secret_token:
  aaf_rc_login_url:

staging2:
  <<: *common
  hostname: https://ic2-hcsvlab-staging2-vm.intersect.org.au
  secret_token:
  aaf_rc_login_url:

test:
  <<: *common
  hostname: https://hcsvlab.intersect.org.au
  secret_token:
  aaf_rc_login_url:

production:
  <<: *common
  hostname: hostname.com
  secret_token: REPLACE_ME
  aaf_rc_login_url: https://rapid.aaf.edu.au/jwt/authnrequest/research/REPLACE_ME
