:development:
  :hostname: 'dtn2.rdsi-test.intersect.org.au'
  :port: '9092'
  :verify_ssl: false

:qa:
  :hostname: 'dtn-1.rdsi-test.intersect.org.au'
  :port: '9092'
  :verify_ssl: true

:production:

