labels:
  RDF_type: 'RDF Type'
  DC_creator: 'Creator'
  DC_rights: 'Rights'
  http_purl_org_cld_terms_isLocatedAt: 'Is Located At'
  DC_custodian: 'Custodian'
  DC_subject: 'Subject'
  DC_title: 'Title'
  DC_description: 'Description'
  DC_bibliographicCitation: 'Bibliographic Citation'
  DC_title: 'Title'
  DC_abstract: 'Abstract'
  DC_accessRights: 'Access Rights'
  DC_contributor: 'Contributor'
  DC_alternative: 'Alternative Title'
  DC_created: 'Created'
  DC_extent: 'Extent'
  DC_is_part_of: 'Is Part Of'
  DC_isReferencedBy: 'Is Referenced By'
  DC_itemFormat: 'Item Format'
  DC_itemType: 'Item Type'
  DC_language: 'Language'
  DC_sensitivitystatement: 'Sensitivity Statement'
  http_www_loc_gov_loc_terms_relators_OWN: 'Owner'
  DC_temporal: 'Temporal Coverage'
  http_purl_org_cld_terms_dateItemsCreated: 'Date Items Created'