defaults: &defaults
  password_reset_email_sender: kali@intersect.org.au
  account_request_user_status_email_sender: kali@intersect.org.au
  account_request_admin_notification_sender: kali@intersect.org.au

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

qa:
  <<: *defaults

qa2:
  <<: *defaults

staging:
  password_reset_email_sender: jared@intersect.org.au
  account_request_user_status_email_sender: jared@intersect.org.au
  account_request_admin_notification_sender: jared@intersect.org.au
