development:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
test:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
qa:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
staging:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
qa2:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
staging2:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
production:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
cucumber:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"
trove:
  iso639_3_code_lookup_url: "http://www-01.sil.org/iso639-3/documentation.asp?id=%s"