development:
#  url: http://alveo-qa-sesame.alveo.edu.au:8080/openrdf-sesame/
  url: http://localhost:8983/openrdf-sesame
test: &TEST
  url: http://localhost:8983/openrdf-sesame
qa:
  url: http://localhost:8080/openrdf-sesame
qa2:
  url: http://192.168.154.149:8080/openrdf-sesame/
nci:
  url: http://10.0.0.11:8080/openrdf-sesame
staging:
  url: http://10.0.0.26:8080/openrdf-sesame
staging2:
  url: http://localhost:8080/openrdf-sesame
production:
  url: http://localhost:8080/openrdf-sesame
cucumber:
  <<: *TEST
trove:
  url: http://alveo-sesame.alveo.edu.au:8080/openrdf-sesame/
