theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_path: false
theme_advanced_resizing: true
theme_advanced_buttons3_add:
  - fullscreen
plugins:
  - fullscreen

